// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// dtw_rcpp
List dtw_rcpp(NumericVector x, NumericVector y);
RcppExport SEXP _ProjetM2Algo_dtw_rcpp(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(dtw_rcpp(x, y));
    return rcpp_result_gen;
END_RCPP
}
// dtw_sakoe_chiba_rcpp
List dtw_sakoe_chiba_rcpp(NumericVector x, NumericVector y, int radius);
RcppExport SEXP _ProjetM2Algo_dtw_sakoe_chiba_rcpp(SEXP xSEXP, SEXP ySEXP, SEXP radiusSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type radius(radiusSEXP);
    rcpp_result_gen = Rcpp::wrap(dtw_sakoe_chiba_rcpp(x, y, radius));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ProjetM2Algo_dtw_rcpp", (DL_FUNC) &_ProjetM2Algo_dtw_rcpp, 2},
    {"_ProjetM2Algo_dtw_sakoe_chiba_rcpp", (DL_FUNC) &_ProjetM2Algo_dtw_sakoe_chiba_rcpp, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_ProjetM2Algo(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
