# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dtw_rcpp <- function(x, y) {
    .Call(`_ProjetM2Algo_dtw_rcpp`, x, y)
}

