# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dtw_cpp <- function(x, y) {
    .Call(`_ProjetM2Algo_dtw_cpp`, x, y)
}

segmental_dtw_cpp <- function(serie1, serie2, segment_length) {
    .Call(`_ProjetM2Algo_segmental_dtw_cpp`, serie1, serie2, segment_length)
}

dtw_rcpp <- function(x, y) {
    .Call(`_ProjetM2Algo_dtw_rcpp`, x, y)
}

dtw_sakoe_chiba_rcpp <- function(x, y, radius = 1L) {
    .Call(`_ProjetM2Algo_dtw_sakoe_chiba_rcpp`, x, y, radius)
}

